### PR TITLE
resolved issue #8 and issue #36: added charts to country.html and added ds_store to gitignore

### PR DESCRIPTION
**Pull request by benjiww**
Resolved issue #8 and issue #36:

#8 : Added google charts to country.html and a dropdown menu for chart selection (same as sort type selector on index.html). No flaws aside from:

1) The first load of the chart has no y axis values, but doing anything to the chart (even window resizes) corrects this. Weird, I know. Worth opening an issue to fix this bug.

2) Sometimes the graph will extend the y axis one notch into the negatives, even though this is not possible with vaccine count (can't have negative vaccines administered). Would go nicely with the issue above, but again is just a stylistic problem.

3) Dropdown menu is also not centered on dropdown which looks a little off but I'm unsure of an appropriate front end fix. Not essential to open an issue.

#36 : Added .DS_STORE to gitignore.

Cheers.

### CODE REVIEW

**Comment by FlavioAdamo** [comment]
Hi! The charts are not working, i get the following error
image

p.s Just sent you an email

**Comment by benjiww** [comment]
That's weird - it's working fine on my local. I'm not sure what I can suggest, but I will have a research to see if anyone gets the same problem with Google Charts.

Just got your email btw, appreciate you getting in contact - I'll get back to you within the next few days as I'm working this weekend.

Screenshot 2021-05-28 at 22 01 45

**Comment by benjiww** [comment]
UPDATE AGAIN: The following is not true as this HTML code IS included in the commit. I have literally no idea why this is not working for you lol.

------

Update:

I haven't included any google charts scripts in the HTML page, this is surely the issue.

Add the following to the country.html:

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

Not sure why it works for me without this though?

**Comment by FlavioAdamo** [comment]
Pull request accepted!

**Pull request merged**
