### PR TITLE
Aligned the share buttons

### PR DESCRIPTION
**Pull request by godwin-morwin**
Aligned the share buttons and added a background color to the twitter button

### CODE REVIEW

**Comment by FlavioAdamo** [comment]
The twitter and Facebook button are not aligned : 
image

**Comment by godwin-morwin** [comment]
@FlavioAdamo looking into it 🙂

**Comment by godwin-morwin** [comment]
@FlavioAdamo did you change the color and added the Tweeter icon?

**Comment by FlavioAdamo** [comment]
Nope, the twitter icon has always been there and I haven't changed any color.

**Pull request closed without merging**
