### PR TITLE
Delete the share button and replace it with a menu (hamburger on mobile) #22

### PR DESCRIPTION
**Pull request by Saliou1920**
## What?
I've replaced the share button with a menu. It has the contributors and the GitHub pages. For more background, see ticket #22.

## Why?
These changes complete the user login and account creation experience. See #JIRA-123 for more information.

## How?
I'm using Bootstrap to do the heavy lifting.

## Screenshots (optional)

- On Desktop

changeS

- On mobile

changeD

### CODE REVIEW

**Comment by FlavioAdamo** [comment]
You did a really good job, but i would like to change a few things:

- image<br> As you can see the item on the menu are not aligned, is it possible to fix that?
- I think a less bold text  it's better
If you have no time dont worry, those a really simple fix and I can work on it.

**Comment by d4rkener** [comment]
Nice changes

**Comment by Saliou1920** [comment]
Thanks y'all. 
@FlavioAdamo what do you think about this?? 👇
-
https://user-images.githubusercontent.com/60982664/119337465-3ca38400-bc65-11eb-91b8-2eda1c1fa4c1.MOV

**Comment by FlavioAdamo** [comment]
Amazing!

**Comment by Saliou1920** [comment]
Okay👍 I'll push it so that you can review it😊

**Comment by FlavioAdamo** [comment]
Pull request accepted!
The code looks great!

**Pull request merged**
