### PR TITLE
Update country.html

### PR DESCRIPTION
**Pull request by daveliew**
Used "/" in logo anchor href URL to bring users back to homepage.

### CODE REVIEW

**Comment by Colt4D5** [comment]
Curious why you would remove the link back to the homepage from country.html?  There is no "home" button, so this is probably a good feature, no?

**Comment by daveliew** [comment]
Oh @Colt4D5 , I'm not removing the link back to the homepage. 

This is an edit to a previous Pull Request where I used the attribute  'href:"/index.html"', but @FlavioAdamo corrected me to that the attribute should be 'href: "index.html"' instead (thus, this Pull Request which removes the '/")

I'm not sure how I could have resubmitted my previous Pull Request that was closed, maybe that would have been less confusing.

**Comment by daveliew** [comment]
@Colt4D5 ah I see, I should just use "/" directly! Thanks for your comment, learnt something today.

**Comment by Colt4D5** [comment]
Gotcha. No worries. This was my first open-source contribution, so I'm new and thought I was doing something wrong too. Lol

**Comment by daveliew** [comment]
@FlavioAdamo Suggest you use @Colt4D5's pull request, a lot of good stuff there!

@Colt4D5 I'm very raw, have learnt a lot from your submission!

**Pull request closed without merging**
